// The projects, ranked: first by how ready each one is to show, then by
// its scores. Each gets half a screen of picture and half a screen of
// write-up. Facts come from each project's own README and code, and from
// building and running them (October 2026).
//
// status: "live" (running in public), "ready" (shows well as it is),
// "polish" (works; needs a pass before it shines), "rebuild" (a strong idea
// whose core needs reworking).
// demo: a copy that runs right here on the site, in public/demos/.
//
// TODO (Ben): write each "why" in your own words, and adjust the scores.

export const SCORES = [
  { id: "scale", label: "Scale" },
  { id: "depth", label: "Technical depth" },
  { id: "polish", label: "Completeness" },
];

export const STATUS = {
  live: { label: "Live", rank: 0 },
  ready: { label: "Ready", rank: 1 },
  polish: { label: "Needs polish", rank: 2 },
  rebuild: { label: "Rebuilding", rank: 3 },
};

const PROJECT_LIST = [
  {
    id: "chaos",
    name: "Chaos Coaching",
    tagline: "An AI running coach that plans each athlete's week",
    url: "https://chaoscoaching.co",
    when: "2026–present",
    status: "live",
    scores: { scale: 6, depth: 9, polish: 9 },
    what: "A training platform that plans each athlete's week from their synced training, notes, and goals, then adjusts as the week goes.",
    why: null,
    how: [
      "Strava webhooks bring in every run as it's recorded.",
      "Claude writes the plan; injury-prevention rules in code check it before an athlete ever sees it, so the plan can't skip them.",
      "Stress-tested against 13 simulated athletes.",
    ],
    stats: [
      ["24,000", "lines of code"],
      ["298", "automated tests"],
      ["13", "simulated athletes"],
    ],
    tools: ["Node", "Express", "SQLite", "Claude API", "Strava API", "Stripe", "Docker"],
    // the app's code is private; this page only ever shows screenshots
    shot: { src: "projects/chaos.jpg", alt: "Chaos Coaching's home page, showing this week's plan" },
  },
  {
    id: "world-navigation",
    name: "World Navigation",
    tagline: "An infinite world, generated from a single number",
    url: "https://bconlin.com/demos/world-navigation/",
    demo: "demos/world-navigation/index.html",
    when: "2026",
    status: "ready",
    scores: { scale: 8, depth: 9, polish: 9 },
    what: "A procedurally generated world you can pan and zoom forever. The same seed builds the same world, cell for cell, on any machine. Found a colony and watch it forage, settle, and wear roads between its towns.",
    why: null,
    how: [
      "Every 32 m cell carries elevation, temperature, humidity, biomass, slope, water depth, and upstream catchment, modeled physically, so deserts land in rain shadows and rivers grow as they gather tributaries.",
      "The generator is Rust compiled to WebAssembly with no dependencies; the viewer draws it with WebGL2.",
      "Colonists are a separate simulation: they deplete the land they forage, found settlements, trade, and haul stone.",
    ],
    stats: [
      ["65 KB", "world generator"],
      ["32", "automated tests"],
      ["7", "map views"],
    ],
    tools: ["Rust", "WebAssembly", "TypeScript", "WebGL2"],
    shot: { src: "projects/world-navigation.jpg", alt: "A generated coastline with forests, beaches, and branching rivers" },
  },
  {
    id: "swarm",
    name: "SwarmSim",
    tagline: "Flocking birds simulated on the GPU",
    url: "https://bconlin.com/demos/swarm/",
    demo: "demos/swarm/index.html",
    when: "2026",
    status: "ready",
    scores: { scale: 8, depth: 8, polish: 8 },
    what: "A flocking simulation in the browser. Each bird steers only by the birds around it. The flocks chase invisible targets and scatter from hawks.",
    why: null,
    how: [
      "Wrote the physics as WebGPU compute shaders, so the bird data never leaves the graphics card.",
      "Found each bird's neighbors with a spatial hash rebuilt on the GPU every frame, so a step costs the same per bird at any flock size.",
      "Replaced one fixed center of gravity with moving targets and hawks, so flocks split and merge instead of circling one point.",
      "Reworked how birds keep their distance, cutting crowding from about 6,500 neighbors per bird to under 20.",
    ],
    stats: [
      ["400,000", "birds in my test"],
      ["6", "presets"],
      ["262,144", "hash buckets"],
    ],
    tools: ["WebGPU", "WGSL", "JavaScript"],
    shot: { src: "projects/swarm.jpg", alt: "Flocks of birds stretched into ribbons against a black sky" },
  },
  {
    id: "labkit",
    name: "Life at a Billion Cells",
    tagline: "Conway's Game of Life, a billion cells at a time",
    url: "",
    when: "2026",
    status: "ready",
    scores: { scale: 9, depth: 7, polish: 9 },
    what: "Conway's Game of Life on boards of millions to billions of cells, with a nine-panel report of what happened on every run: population, births and deaths, how life spread, and how fast the engine went.",
    why: null,
    how: [
      "Cells are packed as bits, so a billion cells fit in about 119 MiB per buffer.",
      "The board is split into tiles across every core: 1.07 billion cells at about 560 ms a generation, 1.8 billion cells a second.",
      "One command builds its own environment and runs; tests, linting, and type checks run in CI.",
    ],
    stats: [
      ["1.07B", "cells per board"],
      ["1.8B", "cells per second"],
      ["180", "automated tests"],
    ],
    tools: ["Python", "NumPy", "Matplotlib", "pytest", "GitHub Actions"],
    shot: { src: "projects/labkit.jpg", alt: "A nine-panel dashboard from a billion-cell run" },
  },
  {
    id: "rush-hour",
    name: "Rush Hour",
    tagline: "Traffic where every car is its own driver",
    url: "https://bconlin.com/demos/traffic/",
    demo: "demos/traffic/index.html",
    when: "2026",
    status: "ready",
    scores: { scale: 5, depth: 8, polish: 8 },
    what: "A traffic simulation where each vehicle routes itself, picks lanes, judges gaps, and negotiates junctions, on a road network you can draw and edit live.",
    why: null,
    how: [
      "Following distance comes from the Intelligent Driver Model; lane changes from MOBIL, weighing each driver's gain against the cost to the car behind.",
      "Red lights, junction conflicts, and the car ahead all feed the same equation, so braking is always smooth.",
      "A headless soak test runs every preset and checks for overlaps, deadlocks, and bad numbers.",
    ],
    stats: [
      ["0.07 ms", "per 1,000 cars per step"],
      ["3", "road presets"],
      ["59 KB", "whole app"],
    ],
    tools: ["TypeScript", "Canvas", "Vite"],
    shot: { src: "projects/traffic.jpg", alt: "A roundabout with queues on the approaches and cars flowing around the ring" },
  },
  {
    id: "autonomous-city",
    name: "Autonomous City",
    tagline: "Ten thousand self-driving cars, routed through a generated city",
    url: "",
    when: "2026",
    status: "polish",
    scores: { scale: 9, depth: 8, polish: 6 },
    what: "A deterministic simulation of autonomous vehicles routing through a procedurally built city, with a 2D editor for painting roads and buildings.",
    why: null,
    how: [
      "Every road cell has one travel direction, and A* routing can't produce a route against it.",
      "Hazards block cells and force only the affected vehicles to replan, not the whole fleet.",
      "The simulation core has no engine dependency, so a run you watch and a run you batch give identical results from the same seed.",
    ],
    stats: [
      ["1,800×", "real time, 1,000 cars"],
      ["10,000", "cars on a 1,000×1,000 grid"],
      ["153", "automated tests"],
    ],
    tools: ["Rust", "Bevy"],
    shot: { src: null, alt: "" },
  },
  {
    id: "quant",
    name: "From a Spreadsheet to Neuroevolution",
    tagline: "Four rebuilds of one question: can a machine learn to trade?",
    url: "",
    when: "2025",
    status: "polish",
    scores: { scale: 6, depth: 8, polish: 5 },
    what: "It started as an Excel backtester and ended as a population of neural networks evolving their own trading strategies.",
    why: null,
    how: [
      "Excel and VBA: randomized indicator weights, replayed day by day across dozens of stocks.",
      "Python: thousands of those trials run in parallel with Monte Carlo, logged to SQLite, then a paper-trading bot on Alpaca.",
      "Neuroevolution: 250 networks per generation, mutating weights and shape, scored against the S&P 500 with fees and a diversification penalty, over 743 generations.",
      "Tested on a held-out year: 12 of 20 top strategies beat the S&P 500, but only 2 beat simply holding the same stocks, so most of the edge was in the picks, not the timing.",
    ],
    stats: [
      ["743", "generations"],
      ["250", "strategies each"],
      ["100", "stocks traded"],
    ],
    tools: ["Python", "NumPy", "SQLite", "Excel VBA", "Polygon API", "Alpaca API"],
    shot: { src: "projects/quant.jpg", alt: "Chart of best and median fitness rising over 743 generations" },
  },
  {
    id: "worldsim",
    name: "WorldSim",
    tagline: "A voxel world of people who are born, pair off, build, and die",
    url: "",
    when: "2026",
    status: "polish",
    scores: { scale: 5, depth: 8, polish: 4 },
    what: "Agents living in a voxel world. They score their options, pursue the winner, raise children who inherit their genes, and die of hunger, violence, or old age. Chopping and building really change the world.",
    why: null,
    how: [
      "Each agent weighs its needs with a utility function, then carries out the winning goal as a behavior tree.",
      "Genes pass from parents to children, so traits drift over generations.",
      "The simulation runs on a fixed tick, so it behaves the same at 1× and 100× speed.",
    ],
    stats: [
      ["6,800", "lines of Rust"],
      ["1×–100×", "same results"],
      ["1", "mutable world"],
    ],
    tools: ["Rust", "Bevy"],
    shot: { src: null, alt: "" },
  },
  {
    id: "minecraft",
    name: "Minecraft AI",
    tagline: "Bots that learn to play, and a colony that settles a world",
    url: "",
    when: "2026",
    status: "polish",
    scores: { scale: 5, depth: 7, polish: 5 },
    what: "A Minecraft agent ready for reinforcement learning: it joins your world as a player, sees through a ray-cast camera, and acts from a set of discrete moves. A second mode runs a colony of bots that gather, farm, and build houses from blueprints.",
    why: null,
    how: [
      "Each step the bot sees 692 numbers (its state, a camera of rays, nearby blocks, entities, and inventory) and picks one of 17 actions.",
      "A WebSocket bridge lets a Python trainer drive it, with PPO from stable-baselines3.",
      "Rewards and goals (parkour, survive, collect, hunt) are plain, editable files.",
    ],
    stats: [
      ["692", "inputs per step"],
      ["17", "actions"],
      ["6", "built-in goals"],
    ],
    tools: ["JavaScript", "Mineflayer", "Python", "stable-baselines3"],
    shot: { src: null, alt: "" },
  },
  {
    id: "everything",
    name: "Everything",
    tagline: "A tree of all knowledge, to learn as deep or as wide as you like",
    url: "",
    when: "2025",
    status: "rebuild",
    scores: { scale: 8, depth: 7, polish: 3 },
    what: "The goal is a tree of everything, where every topic has an article to learn from and flashcards on spaced repetition, so you can go deep on one branch or follow breadth. The database and the topic browser work. The first AI pipeline for writing articles was too simple for Wikipedia's tangle, so that layer is next.",
    why: null,
    how: [
      "Wikipedia's category dumps are parsed into PostgreSQL: 30,931 topics with definitions.",
      "Every ancestor of every topic is precomputed (725,504 rows), so a whole branch loads in one query.",
      "Links are split into 8 partitions, with fuzzy name search on every topic.",
    ],
    stats: [
      ["30,931", "topics"],
      ["725,504", "ancestor links"],
      ["8", "partitions"],
    ],
    tools: ["PostgreSQL", "TypeScript", "Express", "React", "Python"],
    shot: { src: "projects/everything.jpg", alt: "The topic browser at the root of the tree" },
  },
  {
    id: "gravity",
    name: "Barnes-Hut Gravity",
    tagline: "Galaxies forming and colliding, one tree of forces at a time",
    url: "",
    when: "2026",
    status: "polish",
    scores: { scale: 4, depth: 7, polish: 3 },
    what: "A gravity simulator with five starting setups: a spiral galaxy, two galaxies colliding, a globular cluster, a protoplanetary disk, and a dark matter halo.",
    why: null,
    how: [
      "A Barnes-Hut tree groups distant bodies so forces cost N log N instead of N squared.",
      "Leapfrog integration keeps the energy of each orbit steady over time.",
      "Colors come from density, so structure shows up as it forms.",
    ],
    stats: [
      ["5", "presets"],
      ["N log N", "force cost"],
      ["755", "lines of Python"],
    ],
    tools: ["Python", "NumPy", "pygame"],
    shot: { src: null, alt: "" },
  },
  {
    id: "brain",
    name: "Brain Map",
    tagline: "A tower of goals that tells you how far along you are, and how sturdy",
    url: "",
    when: "2026",
    status: "polish",
    scores: { scale: 3, depth: 5, polish: 5 },
    what: "A self-organizing map of what you're working toward. It answers two questions separately: how far along you are, and how well that progress is held up.",
    why: null,
    how: [
      "Bubbles grow as you log progress; edges mean one thing holds up another.",
      "Pace is a least-squares fit over the last 28 days, with an ETA and a flag when something stalls.",
      "It finds the weak legs: anything resting on a single support.",
    ],
    stats: [
      ["28", "days of pace"],
      ["0", "dependencies"],
      ["2", "separate scores"],
    ],
    tools: ["Python", "Tkinter"],
    shot: { src: null, alt: "" },
  },
];

const avg = (p) => (p.scores.scale + p.scores.depth + p.scores.polish) / 3;
export const PROJECTS = [...PROJECT_LIST].sort((a, b) => STATUS[a.status].rank - STATUS[b.status].rank || avg(b) - avg(a));
